#!/usr/bin/env ruby

puts "Received data there"

path, repo, sha, *_ = *ARGV.reverse

class BuildFailed < RuntimeError
end

def exe(command)
  puts "\e[33m[#{Time.now}] #{command}\e[0m"
  system command
  raise BuildFailed, "Command failed: #{command.inspect}" if $?.to_i != 0
end

def run(path, repo, sha)

  unless File.exist?(path)
    exe "git clone #{repo} #{path}"
  end

  Dir.chdir path do

    exe "git clean -fdx"
    exe "git fetch"
    exe "git checkout #{sha} -q"

    if File.exist?(".mustacci")
      puts "Running .mustacci file"
      exe "./.mustacci"
    elsif File.exist?("Gemfile")
      puts "Gemfile found, installing rake with bundler"
      exe "gem install bundler"
      exe "bundle install"
      exe "bundle exec rake"
    else
      puts "Just running rake"
      exe "rake"
    end

    exe "git notes --ref=mustacci add -m 'Build successful (#{Time.now})' #{sha}"
    exe "git push origin refs/notes/mustacci"

  end
end

begin
  run(path, repo, sha)
rescue BuildFailed => error
  STDOUT.puts "\e[31m#{error}\e[0m"
  Dir.chdir path do
    exe "git notes --ref=mustacci add -fm 'Build failed (#{Time.now})' #{sha}"
    exe "git push origin refs/notes/mustacci"
  end
end
