#!/usr/bin/env ruby

require 'json'
require 'yaml'
require 'zmq'
require 'pty'
require 'websocket_client'

QUEUE = "tcp://127.0.0.1:9000"
CONFIG = YAML.load(File.open("repositories.yml"))


def run(data, client)
  payload = JSON.parse(data)
  repo = payload["repository"]["url"]

  puts "[#{Time.now}] Building #{repo.inspect}"

  path = CONFIG[repo]["path"]

  PTY.spawn "./script/runner #{repo} #{path}" do |read, write, pid|
    read.each_char do |char|
      # TODO send this to a websocket
      print char
    end
  end

end


puts "Listening for builds on #{QUEUE}"

context = ZMQ::Context.new(1)
inbound = context.socket(ZMQ::UPSTREAM)
inbound.bind QUEUE

WebSocketClient.create("ws://localhost:10081/") do |client|
  loop do
    data = inbound.recv
    puts "Received data here!"
    begin
      run data, client
    rescue Exception => error
      puts error.class
      puts error
      puts *error.backtrace
      exit
    end
  end
end
